### ISSUE TITLE
Best practice of sharing data in lexibank framework

### ISSUE THREAD

**Issue by LinguList** [lexibank/lexibank#125]
I am struggling with a couple of questions, while preparing the data for the lexibankification of the Dogon paper with Abbie (small study, initial tests):

* https://github.com/lingpy/language-island-paper

As we also have code, we need to put our analyses somewhere, but ONLY submitting data in CLDF is also not necessarily good for backwards compatibility, so it seems better to make a lexibank package, as I did now. I placed the code in a code/ folder, so people can work from there, with an additional README in there. It seems to be fine like this in most part, but do we have any alternative suggestions or ideas on how to recommmend that people submit their data? Should they maybe make a lexibank-package with cldf INSIDE their bigger code folder?

**Comment by xrotwang** [comment]
Yes, wouldn't this make sense? You often see these recommended project dir
layouts, with one folder data. CLDF datasets would go in There, I think.

Johann-Mattis List <notifications@github.com> schrieb am Mi., 22. Aug.
2018, 15:21:

**Comment by xrotwang** [comment]
The alternative would be what we did with clics: have standalone lexibank
data sets which are installed into the analysis environment.

Robert Forkel <xrotwang@googlemail.com> schrieb am Mi., 22. Aug. 2018,
15:41:

**Comment by LinguList** [comment]
okay, this only has one problem by now: cldf datasets are installed by their folder name, or at least, we'll have name clashes, as the current CURATE API will prompt me for "language-islands-paper" by the folder name, so DATA or CLDF or LEXIBANK would lead to nameclashes, but this needs probably to be fixed from within the lexibank API, right? That we use the name by which it is installed, not the name of the folder...

**Comment by LinguList** [comment]
If we change this part (folder name can be arbitrary, but internally, we fix them), we could easily have a structure:

```
/data # lexibank dataset
setup.py
etc.
/README.py
customcode.py
etc.
```
I'd prefer this over my current solution, as it is basically the code I want to expose, and the lexibank data is just an extra service. I'd even say: we should call it "lexibank", the folder.

**Comment by xrotwang** [comment]
Hm, I don't know. When I proposed the `/data` directory, I thought about arbitrary, non-lexibank CLDF datasets. For lexibank datasets it's different. They should (must?) be curated in a separate repository and brought into a project either by installing or by cloning them.

I'd hope that the line between all-purpose lexibank data and custom analysis code is easy enough to draw in most cases (although it's easy to imaging that the same functionality may be needed for custom code and lexibank curation code).

So in the case of this paper, I'd say you'd have to share **two** things (probably from two repositories): The lexibank dataset and the analysis. While this means more work for you, I think that even that separation adds value, because it signals what you see as *custom* or *all-purpose*.

**Comment by LinguList** [comment]
Okay, what is probably still a problem in the lexibank code is this line in dataset.py

```
    @lazyproperty
    def id(self):
        return self.dir.name
```

This forces us to give a specific folder name for each dataset, although we don't check whether folder name is equal to install name (which it is not by now). 

What I was thinking:

I could submit both the lexibank datasets and the code we use in the same repository to zenodo/etc., if we change the id creation and make it based on the ds-name in the setup.py. This allows me to submit a python package as I did it now (by adding a `code/` folder where I have my custom code), or, what is probably better, by placing a `lexibank` folder into my normal repository where i have the lexibank package then. Or is there anything that speaks against this practice? I would still have the two packages in some sense, but it would be a single entry in Zenodo, which I'd prefer. Installing this is as straightforward as installing any other lexibank dataset. 

In general: the `id=self.dir.name` is a bit shaky, right? Since we have can have different folder and install names, but I don't know how to change the line to take the installation name as ID...

**Comment by LinguList** [comment]
Okay, one more argument for this procedure to have code for data preparation and the dataste in lexibank in the same folder is: if we change the code or update it, we don't have to make a new lexibank version by manually copying the file there, we can just update at once. And in this case, the code was also what we used to create the well-balanced dataset we look into in the end...

**Comment by LinguList** [comment]
It is revealing: all shared features of Pakistan are a couple of letters shared with Austrian SL and German SL and American SL, so NO shared innovation or whatever.

**Comment by LinguList** [comment]
BTW, in lingpy, this operation is as easy as:

```python
In [1]: from lingpy import *

In [2]: wl = Wordlist('power_edited.tsv')

In [3]: wl.add_entries('doculect_name', 'doculect', lambda x: x)

In [4]: wl.add_entries('doculect', 'doculect_translation', lambda x: x.split(' ')[0]+'_SL', override=True)

In [5]: wl.output('tsv', filename='power_edited')
```

I should probably write a short cookbook on this at some point.

**Comment by xrotwang** [comment]
I'm not convinced yet. Yes, the raw "take the name of the parent directory" approach was a bit hacky, because pip cloned the repository into a directory with the package name, not the repos name, but I already fixed this. Basically, the idea is that the repository name should be the dataset id:
- this is rather straightforward and means that to some extent GitHub already prevents name clashes,
- there's also no need to repeat the ID in the package somewhere, because it can be discovered from withi the code (note that this is not the case for stuff in `setup.py`, because that's not available to the package after installation)

And while this may not be the case up to the publication of a paper (i.e. up to version 1.0 of data and code), it seems totally plausible that afterwards code and data will develop separately, so keeping them in separately versioned places makes a lot of sense to me.

**Comment by LinguList** [comment]
Sorry, just pushed this without PR: https://github.com/lexibank/pylexibank/commit/fa42fcf859c91b18f6f12c15d1a9869cc7ad2704#diff-b65f6469d8d38eec3a2843b14e3705cbL174

But I think we can also live with this, right? Independent from what we should do.

**Comment by LinguList** [comment]
Or does it break any tests by any chance, if we go for dataset ID as module name?

**Comment by LinguList** [comment]
But regarding the issue of dataset etc., I see far more usecases where users do a lot with a dataset first and THEN they would add CLDF export on top, in fact all datasets on which I work now: Sino-Tibetan, Dogon, also Sign language data. What I do often nowadays is putting a lot of custom code in the raw folder, but this is also not really elegant. 

For me, the concrete question is: if I have a dataset in CLDF, and in CLDF only, because I did not use the lexibank curation workflow, can I still load it in lexibank? In this case, I wouldn't bother preparing CLDF with lexibank, but rather prepare it directly.

Another usecase: if I have a custom repository, with a good name (I agree that those should be somehow follow the recommendations), and I put a lot of files inside, with some custom README: as long as I put the setup.py, the raw, the etc, it would be all the same for lexibank, what exactly I do with all the data around it, right? I'm just thinking: for those producing a lot of dataset in lexibank-cldf, it would be useful if it was more like adding the three to four custom python scripts and being able to leave their data in one place.

**Comment by xrotwang** [comment]
lexibank datasets don't need to be curated using pylexibank, i.e. they may only consist of the `cldf` directory, the python module and the `setup.py`. They may also contain any other directories, so I don't see a need to put analysis code into `raw`.

What I wouldn't want to see is
- custom analysis code that uses the data from `raw` rather than `cldf` (this may acceptable for some time to come until lingpy fully supports cldf, but eventually should go away)
- too much stuff distributed together with a lexibank dataset that is hard to make sense of. If all code included in the dataset does make sense in the light of a published paper, that's ok though.

**Comment by xrotwang** [comment]
I hope I put that into documentation already somewhere, but here's the two main functionalities I see:

1. The curation workflow: Basically everything from creating a dataset skeleton to running `makecldf`.
2. The data aggregation functionality, i.e. the way we used pylexibank in clics, as a tool to create a custom selection of lexical data from lexibank datasets for a particular analysis. In the future, I see this functionality expanding, e.g in the direction Olivier(s) asked for, i.e. limiting selection to certain families, etc.

**Comment by xrotwang** [comment]
__module__ could work, I guess. Will have to test for a bit, though. It
shouldn't behave differently under different situations of importing the
code e.g.

Johann-Mattis List <notifications@github.com> schrieb am Do., 23. Aug.
2018, 07:25:

**Comment by xrotwang** [comment]
Regarding data annotation functionality: I think ideally this should work with CLDF. Reading a dataset, adding a column to any table and writing it with updated data and data description already works - if not smoothly enough, we should work on a better API in `pycldf`. Whether this derived dataset should be published as separate dataset, or alongside the source dataset (e.g. putting the source CLDF into `raw`), ... is rather a policy question and not something we need technical solutions for, I think.

**Comment by LinguList** [comment]
Okay, but if you say: the ID is the folder name, than this means, we should check if folder name and the setup installation name are the same, otherwise we also create inconsistencies. The problem here is: folder names can contradict the standards of alphanumeric IDs (if we have them), etc. So if we discard the `__module__` suggestion, we need to add a check that foldername/repository-name and name in `setup.py` are identical (minus `lexibank_`).

**Comment by LinguList** [comment]
I'd use the current lingpy functionalities for data manipulation, as they are convenient for me. So what is missing is a much more flexible export to cldf that would render all columns that are in a dataset. Currently, only specific parts of the data are exported to cldf, but this is obviously not what we need during stages of data creation.

**Comment by xrotwang** [comment]
Yes, you are right that some kind of consistency check between `setup.py` and repository name is needed. But I also think that your use case is somewhat special (or at least only typical for dataset creators). The typical dataset re-use use cases are
- you clone a repository you are interested in, and then install (in this case, you have full local control over what the dataset ID will be, because you can choose to clone to an arbitrary directory)
- you install directly from GitHub using `pip install -e git+https://...` - again you'd have full control via the `egg` parameter

 In both cases, the default should yield the same ID, namely the repository name.

**Comment by xrotwang** [comment]
AFAIKT GitHub forks cannot have different names than the original repositories. So I'd prefer changing the repository name before publication. We also have the policy of not creating releases from the lexibank forks as long as the source repositories are actively maintained. So you'd create releases from your repository, I guess.

**Comment by SimonGreenhill** [comment]
explicit is better than implicit: could we just define id in `Dataset`? If it's not defined, then default to the current behavior.

**Comment by LinguList** [comment]
Renaming is possible, I just tested it. But I don't insist on not renaming it, I just also see the problem of naming if it's not explicit.

**Comment by tresoldi** [comment]
I think you can rename with `set-url` on origin, but it would be against it. Too much potential for errors and conflicts.

**Comment by LinguList** [comment]
AND: I just tested, that I can use a simple workaround for my usecase, by keeping my repository, but using the `src` repository for installation, as we do now in other projects as well:

```
src/
    lexibank_hantganbangime/
        __init__.py # former "lexibank_hantganbangime.py"
        raw/
```

This gives me a) the namespace we need for lexibank, AND it allows me to just have my normal repository with some code, where I then justt add teh setup.py and the "src" repo. Since this is compatible with all we're doing now, I'd say: this is a solution that doesn't hurt anybody.

**Comment by xrotwang** [comment]
@SimonGreenhill I agree with explicit being better than implicit. But then we should go all the way and not have a fallback to implicit behaviour. So from my POV I think we should decide between
- the current behaviour, using the directory/repository name and
- setting an ID explicitly in the `Dataset` class definition.

The only real disadvantage of the second option I see, is that it requires python tools (or at least knowledge) to discover the ID of a dataset. But I guess that's acceptable, because the dataset ID only plays a role in lexibank based workflows, where at least the SQLite db is created using `pylexibank`. Maybe it's even beneficial to disallow "guessing" of dataset IDs; i.e. people interested in using the SQLite db would have to create this db using `pylexibank` and then have a look at dataset IDs in the `dataset` table.

**Comment by xrotwang** [comment]
@LinguList I think your workaround rather serves as an example why we should adopt @SimonGreenhill 's proposal, since it goes counter the intuition that the repository name should be the name of the containing folder.

**Comment by xrotwang** [comment]
@SimonGreenhill I found one more disadvantage: If the dataset ID is defined explicitely - and unchangeably - in the dataset itself, it means making sure these IDs are chosen such as to avoid collisions becomes imperative - possibly requiring some sort of dataset registry to dole out IDs.

**Comment by LinguList** [comment]
Okay, I opt for solution 2, as I find it convenient to keep separate names for the repo, and just have the repository as part of a larger SI package (whcih WILL contain code, but also graphs, maps, etc.). If I have to make two packages in the future for all things I do, this will be a bit annoying, and I think it'll also scare off early adopters.

**Comment by xrotwang** [comment]
My idea for CLDF datasets in general was to use [DCAT](https://www.w3.org/TR/vocab-dcat/) metadata; i.e. datasets should include such metadata which can be harvested to create a global catalog.

**Comment by xrotwang** [comment]
I also think we shouldn't wire GitHub in too heavily. The longterm access to lexibank datasets is via ZENODO, after all. So the github URL may be just one `dcat:accessURL` for a dataset.

**Comment by SimonGreenhill** [comment]
Ah ok. Well how about we live without a registry until it becomes a problem?

**Comment by xrotwang** [comment]
@SimonGreenhill I agree. What we should do, though, since we will have to create new releases for all datasets including th dataset ID explicitly: Add as much DCAT metadata as possible into the CLDF datasets (preferably via `pylexibank`), so that post-hoc catalog/registry creation can be as simple as going through all datasets in the lexibank community on ZENODO.

**Comment by SimonGreenhill** [comment]
sounds good -- sorry for the extra work :)

**Comment by LinguList** [comment]
So if you point me how to address this, I can also add ids for some datasets, starting from clics. But I'm glad we found a solution that gives me more flexibility: not all of supmat is cldf, at least not for now, so it feels "elegant" to just add a setup.py script to an otherwise "normal" supmat package.

**Comment by xrotwang** [comment]
Will try to push out a pylexibank release tonight, and a couple of updated
datasets as examples.

Johann-Mattis List <notifications@github.com> schrieb am Do., 23. Aug.
2018, 18:26:
