### ISSUE TITLE
A global bibtex for datasets accepted in lexibank?

### ISSUE THREAD

**Issue by LinguList** [lexibank/lexibank#157]
Given the problems we have in maintaining some consistency with datasets, I was thinking why we can't make a global bibtex and a `datasets.tsv` file that we populate and update with new versions during each release cycle? 

This would have the disadvantage of being more work, but have the advantage of:

1. allowing us to also make clear how we think datasets should cited
2. make sure we list all sources of the original dataset consistently (not the sources that are pulled into the datasets, of course, but the "how to quote the original dataset")
3. make sure we can handle contributors
4. make sure to check explicitly if a dataset for a release cycle has been actually installed on a computer

I would think of this similar to concepticon:

1. one bibtex file, where we can then also control that it is good style (avoiding `misc` types, spellilng out names completely, avoiding initials)
2. one `datasets.tsv` file where we can summarize some basic info on the datasets, the contributors, the source, etc.

Disadvantage of this procedure: a dataset can be independently in CLDF and in our lexibank cycle, also with info, so it may seem repetitive, but the advantage is that we can harmonize the way in which we actually provide information as per dataset, and that we also keep more rigorously track of what we have.

**Comment by xrotwang** [comment]
I wouldn't want to maintain a registry of datasets other than the Zenodo community. So if we want more and better metadata about datasets, this should happen at Zenodo (or within datasets). There's still multiple options to do this, I think, e.g. requiring `dc:bibliographicCitation` to be a BibTeX record, or making sure the metadata maintained by Zenodo is complete enough so that what Zenodo recommends for citation is what we want. The latter point actually also hightlights a problem any registry maintained by us would face: The main access to datasets would/should happen through the DOI - which is the persistent identifier after all. The DOI registry maintains metadata as well, and recommends ways of citing. If their recommendation isn't consistent with ours, this would be bad.

**Comment by LinguList** [comment]
Okay, in this case, we would have to sit down and think of basic information/styles that we would require to be present before we add a dataset to our Zenodo community. E.g.:

1. consistent title
2. identifier
3. authors
4. compilors / contributors / maintainer (i.e. the person who makes the lexibank), but in an explicit form, that would also override github contributors, as those may be betraying 
5. citation in bibtex (ideally something that quotes the original dataset and has the DOI part as extra information, or some `@incollection` as part of lexibank)
6. version (this is anyway done by zenodo)

As, for practical reasons, a dataset is at times differently quoted than is the paper where it is used, and this is intended. E.g., we have the ST database for Sino-Tibetan [sagartst](https://github.com/lexibank/sagartst) but with different contributors than those who wrote the paper, and also accordingly different responsibilities. I guess we should quickly decide when we meet how we want to treat a dataset in lexibank: as an `@incollection` with us as editors, as an `@online` collection following `biblatex` practice, with additional roles (biblatex has roles like `translator`, `compiler` etc., so we could list more than just an author). Unfortunately, the community is not up-on-top here, as we saw from Scientific Data also, but we could use the chance to set up standards, as this is increasingly important to also think beyond standard bibtex roles.

**Comment by xrotwang** [comment]
To be honest, I'd hope the next standard is simply providing a DOI, or
alternatively, make sure the metadata retrievable via DOI is ok. While it
may have some justification, I think most of the art of citation is more a
rite of passage than anything else.

Johann-Mattis List <notifications@github.com> schrieb am Mi., 10. Juli
2019, 08:46:

**Comment by xrotwang** [comment]
That isn't to say we shouldn't try our best, but rejecting a dataset from
inclusion in lexibank because it violates the citation style guide would
seem overly harsh to me. Submitting a dataset already means you have done
all the important things right, after all.

Robert Forkel <xrotwang@googlemail.com> schrieb am Mi., 10. Juli 2019,
09:50:

**Comment by xrotwang** [comment]
And one more thing: the library community tries to be on top of all things
metadata. And this struggle doesn't seem attractive enough to make me
wanting to compete 😀

Robert Forkel <xrotwang@googlemail.com> schrieb am Mi., 10. Juli 2019,
09:53:

**Comment by LinguList** [comment]
And the library community is failing extremely in this regard. If you compare the biblatex specification with what they use, e.g., at the MPI to quote papers, this is very disappointing.

**Comment by SimonGreenhill** [comment]
Actually -- we're already distributing requirements.txt with clics3, so one way to do the registry thing is to just put the latest requirements.txt into this repository?

**Comment by xrotwang** [comment]
But not every lexibank dataset may be installable, I.e. a python package
curated on github.
So I'd really like to push the zenodo community as **the** registry, and
its oai-pmh feed as the machine readable catalog.

Simon J Greenhill <notifications@github.com> schrieb am Do., 11. Juli 2019,
16:09:
