### ISSUE TITLE
Dataset names: syntax

### ISSUE THREAD

**Issue by xrotwang** [lexibank/lexibank#2]
Names of dataset repositories are re-used in a couple of places, e.g.
- as IDs and eventually URL components in the lexibank web app,
- as parts of python package names.

Thus, these names should be restricted to a very basic syntax to prevent headaches down the road.

**Comment by tresoldi** [comment]
(pasting previous comment)

Well, `asjp` is an exception as it would be an hypothetical `wiktionary` -- it is neither restricted to a family and it is already a data aggregation. I wouldn't matter closing an eye in this case, but it is important to refer to authors already in the dataset name, so that they know we are actually collaborating and not appropriating (pretty much what @LinguList said on a previous email).

**Comment by LinguList** [comment]
I think we'll need a flexible policy: Think of dsets like NorthEuralex, Uralex, Lexirumah, etc.: they would probably count on being just known as authors of these datasets. But Baidial is another case, as it is Allen2007, who authored it, so in these cases calling it "baidialallen" or "baiallen" would probably be nicer..

**Comment by SimonGreenhill** [comment]
This can be closed now:  Added to the 'policies' information: https://github.com/lexibank/lexibank/wiki
